
const RATE_DEBIT = 2.8  
const RATE_CREDIT = 3.2  
const RATE_INSTALLMENT_SMALLER = 3.8  
const RATE_INSTALLMENT_LARGER = 4.2  

module.exports = { RATE_DEBIT, RATE_CREDIT, RATE_INSTALLMENT_LARGER, RATE_INSTALLMENT_SMALLER }
   